version: '3.7'
services:
  cv:
    image: florianspk/florianspk_cv
    container_name: florianspk_cv
    restart: unless-stopped
    networks:
      - ${NETWORK}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./conf/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./errors:/errors
      - ./conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/apache.conf:/etc/apache2/conf-available/z-app.conf
      - ./src:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      - "traefik.http.routers.florianspk_cv.entrypoints=web,websecure"
      - "traefik.http.routers.florianspk_cv.rule=Host(`florianspk.fr`)"
      - "traefik.http.services.florianspk_cv.loadbalancer.server.port=80"
      - "traefik.http.routers.florianspk_cv.tls=true"
      - "traefik.http.routers.florianspk_cv.tls.certresolver=leresolver"
  strapi_cv:
    image: strapi/strapi
    volumes:
      - ./src:/srv/app
    ports:
      - '1337:1337'
networks:
  traefik_network:
    external: true
