version: '3.7'
services:
  cv:
    image: florianspk/florianspk_cv
    container_name: florianspk_cv
    restart: unless-stopped
    networks:
      - ${NETWORK}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      - "traefik.http.routers.florianspk_cv.entrypoints=web,websecure"
      - "traefik.http.routers.florianspk_cv.rule=Host(`florianspk.fr`)"
      - "traefik.http.services.florianspk_cv.loadbalancer.server.port=8282"
      - "traefik.http.routers.florianspk_cv.tls=true"
      - "traefik.http.routers.florianspk_cv.tls.certresolver=leresolver"
  strapi_cv:
    image: strapi/strapi
    container_name: strapi_cv
    networks:
      - ${NETWORK}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - '1337:1337'

networks:
  traefik_network:
    external: true
